/*******************************************************************************
 * Macro Name: MeanderLine
 * Creator  : Guilhem Ribeill
 *	Create a meandered CPW line

 *
 * Revision History:
 * 22 Jul 2013	Generated by L-Edit
 *******************************************************************************/
#define PI 3.141592653589796

module MeanderLine_macro_module
{
#include <stdlib.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include <malloc.h>
#include "ldata.h"
/* Begin -- Remove this block if you are not using L-Comp. */
#include "lcomp.h"
/* End */

	void MeanderLine(void)
	{
		LCell	pCell	=	LCell_GetVisible();
		LFile	pFile	=	LCell_GetFile(pCell);
		
		float Xc, Yc;
		
		float a, r, b;
		
		float t0, dt;
		
		int N, Nc, Np;
		
		float x_c, y_c;
		
		float XX[2000];
		float YY[2000];
		
		float Lx;
		
		float width;
		
		int i, j, idx;
		
		LPoint *ptArray;
		LLayer pLayer;
		
		LDialogItem Dialog_Items[8] = {{"A", "200"}, {"B", "500"}, {"R", "150"}, {"Xc", "0"}, {"Yc", "0"}, {"N", "4"}, {"Wire Width", "12"}, {"Layer", "Metal" }};
	
		if ( LDialog_MultiLineInputBox ( "Meander Parameters", Dialog_Items, 8 ) )
      {
      	a = atoi(Dialog_Items[0].value);
      	b = atoi(Dialog_Items[1].value);
      	r = atoi(Dialog_Items[2].value);
      	
      	Xc = atoi(Dialog_Items[3].value);
      	Yc = atoi(Dialog_Items[4].value);
      	
      	N = atoi(Dialog_Items[5].value);
      	
      	width = atoi(Dialog_Items[6].value);
      	
      	pLayer = LLayer_Find (pFile, Dialog_Items[7].value);
      	
      }  
      else
      {
      	return;
      }
      
      Nc = 16;
      Np = 0;
      
      Lx = 2*(a + 2*(N+1)*r);
      
      XX[0] = Xc-Lx/2;
      YY[0] = Yc;
      XX[1] = XX[0] + a;
      YY[1] = Yc;
      
      Np =1;
      
      x_c = XX[Np]; y_c = YY[Np]+r;
      t0 = -90;
      dt = 360/4/Nc;
      
      for (i = 1; i < Nc+1; i++)
      {
      	XX[Np+i] = x_c + r*cos((t0+i*dt)*PI/180);
      	YY[Np+i] = y_c + r*sin((t0+i*dt)*PI/180);
      }
      Np = Np+Nc;
      
      XX[Np+1] = 20; YY[Np+1]=30;
      Np = Np+1;
      
      /*for (j=0; j<N; j++)
      {
      	x_c = XX[Np]+r; y_c = YY[Np];
      	t0 = 180;
      	dt = -360/4/Nc;
      
      	for (i = 1; i < 2*Nc+1; i++)
      	{
      		XX[Np+i] = x_c + r*cos((t0+i*dt)*PI/180);
      		YY[Np+i] = y_c + r*sin((t0+i*dt)*PI/180);
      	}
      	Np = Np+i;
      
      	XX[Np+1] = XX[Np]; YY[Np+1]=YY[Np] - b;
      	Np = Np+1;
      	x_c = XX[Np]+r; y_c = YY[Np];
      	t0 = 180;
      	dt = 360/4/Nc;
      
      	for (i = 1; i < 2*Nc+1; i++)
      	{
      		XX[Np+i] = x_c + r*cos((t0+i*dt)*PI/180);
      		YY[Np+i] = y_c + r*sin((t0+i*dt)*PI/180);
      	}
      	Np = Np+i;
      
      	XX[Np+1] = XX[Np]; YY[Np+1]=YY[Np] + b;
      	Np = Np+1;
      }
      	
      x_c = XX[Np]+r; y_c = YY[Np];
     	t0 = 180;
  		dt = -360/4/Nc;
      
      for (i = 1; i < 2*Nc+1; i++)
      {
      	XX[Np+i] = x_c + r*cos((t0+i*dt)*PI/180);
      	YY[Np+i] = y_c + r*sin((t0+i*dt)*PI/180);
      }
      Np = Np+i;
      
      XX[Np+1] = XX[Np]; YY[Np+1]=YY[Np] - b/2 +r;
      Np = Np+1;
      
      x_c = XX[Np]+r; y_c = YY[Np];
     	t0 = 180;
  		dt = 360/4/Nc;
      
      for (i = 1; i < Nc+1; i++)
      {
      	XX[Np+i] = x_c + r*cos((t0+i*dt)*PI/180);
      	YY[Np+i] = y_c + r*sin((t0+i*dt)*PI/180);
      }
      Np = Np+i;
      
      XX[Np+1] = XX[Np]+a; YY[Np+1]=YY[Np];
      Np = Np+1; */
      	
		ptArray = (LPoint*)calloc(Np,sizeof(LPoint));
		
		for (idx=0; idx<Np; idx++)
		{
			ptArray[idx].x = LFile_DispUtoIntU(pFile, XX[idx]);
			ptArray[idx].y = LFile_DispUtoIntU(pFile, YY[idx]);
		}
		
		LObject wire = LWire_New(pCell, pLayer,NULL, 0, ptArray, Np);
		LWire_SetWidth( pCell, wire, 1000*width); 
		
		free(ptArray);

	}

	void MeanderLine_register(void)
	{
		LMacro_BindToMenuAndHotKey_v9_30("Tools", NULL /*hotkey*/, "MeanderLine", "MeanderLine", NULL /*hotkey category*/);
	}

}
MeanderLine_register();
